package com.purewowstudio.bodystats.ui.common.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF0061a6)
internal val md_theme_light_onPrimary = Color(0xFFffffff)
internal val md_theme_light_primaryContainer = Color(0xFFd0e4ff)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
internal val md_theme_light_secondary = Color(0xFF8c5000)
internal val md_theme_light_onSecondary = Color(0xFFffffff)
internal val md_theme_light_secondaryContainer = Color(0xFFffdcbb)
internal val md_theme_light_onSecondaryContainer = Color(0xFF2d1600)
internal val md_theme_light_tertiary = Color(0xFF3c6a00)
internal val md_theme_light_onTertiary = Color(0xFFffffff)
internal val md_theme_light_tertiaryContainer = Color(0xFFb9f475)
internal val md_theme_light_onTertiaryContainer = Color(0xFF0e2000)
internal val md_theme_light_error = Color(0xFFB3261E)
internal val md_theme_light_errorContainer = Color(0xFFF9DEDC)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410E0B)
internal val md_theme_light_background = Color(0xFFFFFBFE)
internal val md_theme_light_onBackground = Color(0xFF1C1B1F)
internal val md_theme_light_surface = Color(0xFFFFFBFE)
internal val md_theme_light_onSurface = Color(0xFF1C1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
internal val md_theme_light_outline = Color(0xFF79747E)
internal val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
internal val md_theme_light_inverseSurface = Color(0xFF313033)
internal val md_theme_light_inversePrimary = Color(0xFF9ccaff)
internal val md_theme_light_shadow = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF9ccaff)
internal val md_theme_dark_onPrimary = Color(0xFF00325a)
internal val md_theme_dark_primaryContainer = Color(0xFF00497f)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFd0e4ff)
internal val md_theme_dark_secondary = Color(0xFFffb86d)
internal val md_theme_dark_onSecondary = Color(0xFF4b2800)
internal val md_theme_dark_secondaryContainer = Color(0xFF6a3b00)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFffdcbb)
internal val md_theme_dark_tertiary = Color(0xFF9ed75c)
internal val md_theme_dark_onTertiary = Color(0xFF1c3700)
internal val md_theme_dark_tertiaryContainer = Color(0xFF2c5000)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFb9f475)
internal val md_theme_dark_error = Color(0xFFF2B8B5)
internal val md_theme_dark_errorContainer = Color(0xFF8C1D18)
internal val md_theme_dark_onError = Color(0xFF601410)
internal val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
internal val md_theme_dark_background = Color(0xFF1C1B1F)
internal val md_theme_dark_onBackground = Color(0xFFE6E1E5)
internal val md_theme_dark_surface = Color(0xFF1C1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE6E1E5)
internal val md_theme_dark_surfaceVariant = Color(0xFF49454F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
internal val md_theme_dark_outline = Color(0xFF938F99)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
internal val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
internal val md_theme_dark_inversePrimary = Color(0xFF0061a6)
internal val md_theme_dark_shadow = Color(0xFF000000)

internal val seed = Color(0xFF6750A4)
internal val error = Color(0xFFB3261E)